---
Name: calendar-locations
After:
  - 'framework/*'
  - 'cms/*'
  - 'calendar/*'
---

# Extensions
Event:
  extensions:
    - CalendarLocationsEventExtension
    
# Admin
CalendarAdmin:
  managed_models:
    - PublicEvent
    - PublicEventCategory
    - PublicCalendar
    - EventLocation
    
EventLocation:
  contactinfo_disabled_sections: ['ContactSection','MailingAddressSection']
  extensions:
    - TkiContactInfoExtension
#Advised to set allowed_countries and perhaps allowed_subdivisions